### Register request
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "email": "borisantonijev@gmail.com",
  "firstName": "Boris",
  "lastName": "Antonijev",
  "password": "Test1234",
  "confirmationPassword": "Test1234"
}

### Login request
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "borisantonijev@gmail.com",
  "password": "Test1234"
}

### Refresh token request
GET http://localhost:8080/api/v1/auth/refresh