### Register request
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "email": "test@gmail.com",
  "firstName": "Srdjan",
  "lastName": "Srdjan",
  "password": "Test1234",
  "confirmationPassword": "Test1234"
}

### Get all users
GET http://localhost:8080/api/v1/users/all

### Login request
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "boris@gmail.com",
  "password": "Test1234"
}

### Logout request
GET http://localhost:8080/api/v1/auth/logout

### Refresh token request
GET http://localhost:8080/api/v1/auth/refresh

### Create Task
# @no-cookie-jar
POST http://localhost:8080/api/v1/tasks
Content-Type: application/json

{
  "description": "Test.",
  "due": "2023-12-11T21:34:19.597523",
  "categoryId": 2,
  "priorityId": 3,
  "statusId": 2
}

### Get all Tasks for User
GET http://localhost:8080/api/v1/tasks?page=1
Content-Type: application/json

### Get all Tasks for User By Category
GET http://localhost:8080/api/v1/tasks/category/1?page=1
Content-Type: application/json

### Get all Tasks for User By Status
GET http://localhost:8080/api/v1/tasks/status/1?page=1
Content-Type: application/json

### Get all Tasks for User By Priority
GET http://localhost:8080/api/v1/tasks/priority/1?page=1
Content-Type: application/json

### Get Task by ID
GET http://localhost:8080/api/v1/tasks/2c67b770-e1e5-4f72-99fd-2dfbb36a3829
Content-Type: application/json

### Update Task
PUT http://localhost:8080/api/v1/tasks/c8d4031a-2159-43ff-8945-0e569f5e53c8
Content-Type: application/json

{
  "description": "Chores",
  "categoryId": 2,
  "priorityId": 1,
  "statusId": 1
}

### Delete Task
DELETE http://localhost:8080/api/v1/tasks/e3175f61-3c8a-4a75-ac15-6a8d4f38f3ec
Content-Type: application/json

### Get all projects
GET http://localhost:8080/api/v1/projects

### Create Project
POST http://localhost:8080/api/v1/projects
Content-Type: application/json

{
  "name": "Test",
  "users": []
}