### Register request
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "email": "borisantonijev@gmail.com",
  "firstName": "Boris",
  "lastName": "Antonijev",
  "password": "Test1234",
  "confirmationPassword": "Test1234"
}

### Login request
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "borisantonijev@gmail.com",
  "password": "Test1234"
}

### Refresh token request
GET http://localhost:8080/api/v1/auth/refresh

### Create Task
POST http://localhost:8080/api/v1/tasks
Content-Type: application/json

{
  "description": "Zacilati loma.",
  "categoryId": 2,
  "priorityId": 1,
  "statusId": 1
}

### Get all Tasks for User
GET http://localhost:8080/api/v1/tasks
Content-Type: application/json

### Get Task by ID
GET http://localhost:8080/api/v1/tasks/2c67b770-e1e5-4f72-99fd-2dfbb36a3829
Content-Type: application/json

### Update Task
PUT http://localhost:8080/api/v1/tasks/2c67b770-e1e5-4f72-99fd-2dfbb36a3829
Content-Type: application/json

{
  "description": "Chores",
  "categoryId": 2,
  "priorityId": 1,
  "statusId": 1
}

### Delete Task
DELETE http://localhost:8080/api/v1/tasks/f50ca7ba-bc13-4ffd-b1b8-debd947a32db
Content-Type: application/json